name: Run Renovate CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour
  push:
    tags:
      - '*v*' # after new version tag

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug token and repo
        run: |
          echo "Repo: ${{ github.repository }}"
          curl -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            https://api.github.com/repos/${{ github.repository }} || echo "Token invalid or insufficient"

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.PAT_GITHUB }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: github
          RENOVATE_TOKEN: ${{ secrets.PAT_GITHUB }}
