name: Tag Submodule

on:
  push:
    paths:
      - 'modules/ec2/**'
      - 'modules/rds/**'
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create timestamp-based tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "Generated tag: $TAG"

          git tag $TAG
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push origin $TAG