name: Tag Submodule

on:
  push:
    paths:
      - 'modules/ec2/**'
      - 'modules/rds/**'
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and push tag
        env:
          GH_USERNAME: VStefanov         # 👈 Replace this with PAT owner's username
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}         # 👈 Your fine-grained PAT
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "Creating tag: $TAG"

          git tag $TAG

          # Use username + token format (NOT x-access-token)
          git remote set-url origin https://${GH_USERNAME}:${GH_TOKEN}@github.com/${{ github.repository }}.git

          git push origin $TAG
